In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
authors = pd.read_csv('authors_all.csv', encoding = 'utf-8', sep = ";")

In [3]:
#subset authors born later than 1830 or null
authors2 = authors[(authors['Birth year'] >1830) |(authors['Birth year'].isnull())]

In [4]:
#subset of authors who died earlier than 1900 or null
authors3 = authors2[(authors2['Death year']>1900)|(authors2['Death year'].isnull())]

In [5]:
#create new column for later calculations
authors3.insert(loc = authors3.shape[1], column ='Year_Latest_Artwork', value = np.nan)

In [6]:
for i in range(authors.shape[0]):
    if (i in authors3.index):
        if(authors3.loc[i].artworks_creation_years is not np.nan):
            year = max(authors3.loc[i].artworks_creation_years.split('|'))
            authors3.at[i, 'Year_Latest_Artwork']= year

In [7]:
#subset authors born later than 1830 or null
authors4 = authors3[(authors3['Year_Latest_Artwork'] > 1900) |(authors3['Year_Latest_Artwork'].isnull())]

In [9]:
#write to csv file
authors4.to_csv('filtered_authors.csv', sep=',', encoding = 'utf-8-sig')

In [8]:
authors4.shape

(32289, 18)

In [14]:
#no records for birth year
authors4['Birth year'].isna().sum()

9547

In [18]:

authors3.type.value_counts()

artiste        31648
anonyme         1446
groupe           666
attribution      124
Name: type, dtype: int64

In [13]:
#out of 31648 individual artists 8130 have their birth dates missing
authors3[authors3.type == 'artiste']['Birth year'].isna().sum()

8130

##We have birth dates for 23518 individual artists

In [16]:
# Some of the artists with type 'artiste' might actually be groups of artists
# They are not easy to google

authors3[(authors3.type == 'artiste') & (authors3['Birth year'].isnull())]

,Id artist,name,name extended,type,Birth year,Death year,Birth city,Birth state,Birth country,Death city,Death state,Death country,Gender,Nationality (original),ID artworks,average_year,artworks_creation_years,Year_Latest_Artwork
8,580000000000223,Dave 2000,NaN,artiste,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,masculin,NaN,580000000001409,NaN,NaN,NaN
15,150000000000763,A.C.E.C.,NaN,artiste,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,non renseigné,NaN,150000000060943,NaN,NaN,NaN
16,9000000000084295,A.C.M.,NaN,artiste,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,masculin,française,280000000002490|280000000002491|28000000000249...,NaN,NaN,NaN
32,140000001212952,Jonathan Martin,NaN,artiste,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,masculin,française,140000001211342|140000001811744,2016.0,2016|2016,2016.0
33,140000001212951,Yu Ji,NaN,artiste,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,féminin,chinoise,140000001211342|140000001811744,2016.0,2016|2016,2016.0
37,140000001212953,Ji-Min Park,NaN,artiste,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,féminin,sud-coréenne,140000001211342|140000001811744,2016.0,2016|2016,2016.0
40,140000001212954,Jo-Ey Tang,NaN,artiste,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,masculin,chinoise,140000001211342|140000001811744,2016.0,2016|2016,2016.0
45,140000000009523,Liliane Simone Abat,NaN,artiste,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,féminin,française,140000000051755,NaN,NaN,NaN
51,240000000000326,John Abbot,NaN,artiste,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,masculin,NaN,240000000010122,1975.0,1975,1975.0
58,250000000000757,H. Abeg,NaN,artiste,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,non renseigné,NaN,250000000014518,1895.0,1895,1895.0
60,200000000002507,Claire Abel,NaN,artiste,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,féminin,française,200000000014353,NaN,NaN,NaN
73,9000000000068385,Elisabeth Abitbol,NaN,artiste,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,féminin,NaN,140000000018966,1985.0,1985,1985.0
78,9000000000068069,Alain Bonnamy,NaN,artiste,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,masculin,française,150000000014073,1973.0,1973|1974,1974.0
79,9000000000068068,Djouhra Abouda,NaN,artiste,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,masculin,algérienne,150000000014073,1973.0,1973|1974,1974.0
80,140000000007399,Michel d' Aboville,NaN,artiste,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,masculin,française,140000000032698,1946.0,1946,1946.0
81,150000000000893,Dirk Jan Rol,NaN,artiste,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,masculin,néerlandaise,150000000059942,1963.0,1963,1963.0
82,150000000000710,Janine Abraham,NaN,artiste,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,féminin,française,150000000059942,1963.0,1963,1963.0
84,9000000000083349,Henry Jacques Le Même,NaN,artiste,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,masculin,française,150000000078790|150000000078791|15000000007878...,1935.0,1927|1927|1927|1927|1927|1930|1927|1930|1927|1...,1949.0
89,580000000000071,Jeanne Abram,NaN,artiste,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,féminin,NaN,580000000003089|580000000002947,1950.0,1950,1950.0
105,110000000038484,Accary,NaN,artiste,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,non renseigné,NaN,110000000038485,NaN,NaN,NaN
108,9000000000085148,Julia Loktev,NaN,artiste,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,féminin,NaN,150000000044503|150000000044504|150000000044505,2004.0,2004|2004|2004,2004.0
111,9000000000081797,André Achard,NaN,artiste,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,masculin,NaN,530000000000626,1972.0,1972,1972.0
112,140000000004156,Eugène Achard,NaN,artiste,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,masculin,française,140000000084761|140000000071894|140000000085223,1846.0,1846|1847,1847.0
120,140000000003942,Achintre,NaN,artiste,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,masculin,NaN,140000000071259,1848.0,1848,1848.0
129,140000000007785,Marie Ackermann,NaN,artiste,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,féminin,française,140000000048081,NaN,NaN,NaN
134,140000000005728,Acloque,NaN,artiste,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,non renseigné,française,140000000084762,NaN,NaN,NaN
142,200000000002836,André-Marie Adam,NaN,artiste,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,masculin,française,200000000016672,NaN,NaN,NaN
144,9000000000077381,François Adam,NaN,artiste,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,masculin,française,250000000001488|140000000049542,NaN,NaN,NaN
315,140000000005238,Annette Coppée,NaN,artiste,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,féminin,NaN,140000000079484,1847.0,1847,1847.0
316,140000000004576,Sophie Coppée,NaN,artiste,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,féminin,NaN,140000000073588|140000000079064,1847.0,1847,1847.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35852,240000000208997,Comité Palestine (Saint-Etienne),NaN,artiste,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,non renseigné,NaN,240000000017295,1969.0,1969,1969.0
35856,140000001854518,Comme ça,NaN,artiste,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,non renseigné,NaN,140000001861376|140000001854525,1998.0,1998|1999|1998|1999,1999.0
35857,580000000000204,Cécile Commerçais,NaN,artiste,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,féminin,NaN,580000000002877,NaN,NaN,NaN
35859,110000000000853,Yves Commère,NaN,artiste,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,masculin,NaN,110000000001536,1960.0,1960,1960.0
35865,140000000008193,Henri-Eugène Compan,NaN,artiste,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,masculin,française,140000000044377|140000000044378,NaN,NaN,NaN
35868,200000000002972,Marcel Paul Charles Compère,NaN,artiste,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,masculin,française,200000000023119|200000000022406,NaN,NaN,NaN
35871,150000000000885,Donald Grove,NaN,artiste,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,masculin,NaN,150000000060941,1943.0,1943,1943.0
35872,150000000000890,Jackson Comstock,NaN,artiste,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,masculin,NaN,150000000060941,1943.0,1943,1943.0
35873,140000000007651,Jean-François Comte,NaN,artiste,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,masculin,NaN,140000000026693,NaN,NaN,NaN
35876,9000000000080086,Christophe Terpent,NaN,artiste,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,masculin,française,140000000068009,1994.0,1994,1994.0
35877,9000000000085032,Philippe Dorain,NaN,artiste,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,masculin,NaN,150000000034764|150000000034765|150000000034766,1993.0,1992|1993|1995,1995.0
35878,140000000007063,Comte,NaN,artiste,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,masculin,NaN,140000000030124,NaN,NaN,NaN
35881,200000000002631,Maurice Eugène Conchon,NaN,artiste,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,masculin,française,200000000020771,NaN,NaN,NaN
35882,140000000008194,Jeanne Condat,NaN,artiste,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,féminin,française,200000000021160|200000000020423|140000000048351,NaN,NaN,NaN
35891,140000000003369,Alphonse Conin,NaN,artiste,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,masculin,française,140000000045613|140000001264754|140000001264761,NaN,NaN,NaN
35893,140000000007652,Georges Connan,NaN,artiste,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,masculin,NaN,140000000032609|140000000032645,1946.0,1946,1946.0
35901,140000000008195,Rose Conscience,NaN,artiste,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,féminin,française,140000000042281,1908.0,1908,1908.0
35905,140000000004422,Alphonse Constant,NaN,artiste,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,masculin,NaN,140000000073005|140000000083713,NaN,NaN,NaN
35907,9000000000073725,"Constant-Brulé (Constant Brulé, dit)",NaN,artiste,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,masculin,française,200000000022390|140000000050762|14000000002861...,1939.0,1937|1937|1938|1940|1941|1942,1942.0
35908,140000000008197,Adèle Constantin,NaN,artiste,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,féminin,NaN,140000000041069,NaN,NaN,NaN
35913,140000000008196,Marie Constantin,NaN,artiste,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,féminin,française,140000000041299|140000000044158,NaN,NaN,NaN
35914,580000000000206,Constantin,NaN,artiste,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,non renseigné,NaN,580000000001592,NaN,NaN,NaN
35924,9000000000073877,Emilie Conte,NaN,artiste,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,féminin,NaN,140000000041485|140000000041566,NaN,NaN,NaN
35925,140000000004739,F. Conte,NaN,artiste,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,masculin,NaN,140000000074273,NaN,NaN,NaN
35936,200000000001395,Philippe Convain,NaN,artiste,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,masculin,française,200000000012493,NaN,NaN,NaN
35943,9000000000084876,Colin Fournier,NaN,artiste,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,masculin,britannique,150000000079540|150000000079541|15000000007954...,2001.0,2000|2003|2000|2003|2000|2003|2000|2003|2000|2...,2003.0
35944,9000000000083811,Peter Cook,NaN,artiste,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,masculin,britannique,150000000079540|150000000079541|15000000007954...,2001.0,2000|2003|2000|2003|2000|2003|2000|2003|2000|2...,2003.0
35946,240000000000264,Desmond De Amil,NaN,artiste,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,masculin,française,240000000012740|240000000244491,NaN,NaN,NaN
35954,9000000000071926,Albert Copieux,NaN,artiste,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,masculin,NaN,140000000014932,NaN,NaN,NaN
35956,140000000004660,Augustine Copin,NaN,artiste,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,féminin,NaN,140000000074029,NaN,NaN,NaN